### ISSUE TITLE
Problema de Segurança em arquivos estáticos

### ISSUE THREAD

**Issue by Joaoaalves** [Joaoaalves/Relatorios-DBS#1]
## Tasks

- [x] Renomear todos arquivos que forem enviados por usuários 
- [x] Permitir apenas arquivos com formatos confiáveis
- [x] Garantir que arquivos só possam ser abertos por usuários logados
- [x] Construir uma estrutura de arquivos dentro do servidor

## Critérios de aceitação

- [x] Envio de arquivo com nome malicioso bloqueado (BurpSuite)
- [x] Envio de arquivo com conteudo malicioso bloqueado (BurpSuite)
- [x] Envio de arquivo com extensões maliciosas bloqueado (BurpSuite)
- [x] Criação de testes para permissões de diferentes tipos de usuários (Pytest)
- [x] Criação de diretório protegido contendo os arquivos que não deverão ser abertos publicamente
