### ISSUE TITLE
Criar Log de Acesso

### ISSUE THREAD

**Issue by Joaoaalves** [Joaoaalves/Relatorios-DBS#2]
## Tasks

- [x] Criar log de acesso por ip
- [x] Criar log de logins por usuário e ip
- [x] Criar log de tentativa de login por usuário e ip

## Critérios de Aceitação

- [x] Automação de testes de login, testando se o IP no log está correto
- [x] Automação de testes de bruteforce, testando se o IP no log está correto
- [x] Automação de testes de acesso, testando se o IP no log está correto
