### ISSUE TITLE
Adicionar WTForms + Recaptcha

### ISSUE THREAD

**Issue by Joaoaalves** [Joaoaalves/Relatorios-DBS#3]
## Tasks

- [ ] Trocar todos inputs de formulários para inputs do WTForms
- [ ] Adicionar Recaptcha
- [ ] Adicionar flask-ipban

## Critérios de Aceitação

- [ ] Testes automatizados para ban de ip
- [ ] Testes automatizados de borda para entradas nos inputs de formulário (pytest)

**Comment by Joaoaalves** [comment]
Recaptcha  -> https://pusher.com/tutorials/google-recaptcha-flask/
Flaks-ipban -> https://pypi.org/project/flask-ipban/
