### ISSUE TITLE
Estruturar Relatórios 

### ISSUE THREAD

**Issue by Joaoaalves** [Joaoaalves/Relatorios-DBS#4]
## Tasks

- [ ]  Estabelecer uma estrutura
- [ ]  Estruturar o banco de dados para receber os relatórios
- [ ]  Criar um template em HTML para a página de relatório

## Critérios de Aceitação

- [ ] Template integrado com banco de dados dinamicamente
- [ ] Banco de dados suportando todos os dados do relatório
