### ISSUE TITLE
Estabelecer API's e Gráficos

### ISSUE THREAD

**Issue by Joaoaalves** [Joaoaalves/Relatorios-DBS#5]
## Tasks

- [ ] Definir dados necessários para ser extraídos das API's
- [ ] Definir API's que serão utilizadas para abastecimento de dados dos relatórios (#4)
- [ ] Definir dados necessários nos gráficos dos relatórios

## Critérios de Aceitação

- [ ] Extrair dados reais de redes sociais utilizando as API's selecionadas
- [ ] Gerar gráficos corretamente com dados reais
- [ ] Construir o primeiro relatório real
